name: Deploy

env:
  SERVICE_NAME: intens-api
  PROJECT_ID: intens-api
  DOCKER_IMAGE_URL: registry.hub.docker.com/repository/docker/nikola418/intens-api

on:
  workflow_run:
    workflows: [ "Push Image" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: '${{ secrets.gcp_sa_key }}'
          project_id: ${{ env.project_id }}
      
      - name: Set Up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
      
      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region eu-west4 \
            --allow-unauthenticated