name: Push Image

on:
  push: 
    branches: [ "master" ]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Package
        run: mvn clean package
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build -t nikola418/intens-api:latest --file Dockerfile
      - name: Docker Push
        run: docker push nikola418/intens-api